---
- hosts: all
  gather_facts: false
  become: true
  remote_user: ansible
  tasks:
    - name: パスワードの複雑さ
      copy:
        src: ./roles/common/files/pwquality.conf
        dest: /etc/security/pwquality.conf
        owner: root
        group: root
        mode: u+rw,g+r,o+r
